### ISSUE TITLE
Redundar connexió a Catnix

### ISSUE THREAD

**Issue by itorres** [guifibages/projecte#1]
- Publicar servidor tunels amb IP 10.228.45.1
- Connexió per VLAN Cabrianes
- Connexió OpenVPN Lluis Millet amb pes extra

**Comment by itorres** [comment]
Dos primers punts tancats en la tasca #4,

@xaviermartinez em caldrien els detalls del router LluisMillet per configurar el nou enllaç.

**Comment by itorres** [comment]
Aconseguit. Ha costat una mica trobar els valors adients pel túnel L2TP, però amb MTU i MRU a 1440 s'estabilitza amb un bon rendiment.

```
/interface l2tp-server
add name=l2tp-lluismillet user=guifibages
/interface l2tp-server server
set default-profile=default enabled=yes max-mru=1440 max-mtu=1440 mrru=1600
```

Afegit cost 100 a la interficie ospf quedant la configuració ospf al router BCN així:

```
/routing ospf instance
set [ find default=yes ] redistribute-bgp=as-type-1 redistribute-static=as-type-1 router-id=10.38.141.77
/routing ospf interface
add network-type=point-to-point
add interface=br_gbospf network-type=point-to-point
add interface=vlan135_gbospf_ether3 network-type=point-to-point
add cost=100 interface=l2tp-lluismillet network-type=point-to-point
/routing ospf network
add area=backbone network=10.228.45.1/32
add area=backbone network=172.25.129.64/30
add area=backbone network=172.25.128.140/30
```

Notifico a @guifibages/sysadmins

**Comment by xaviermartinez** [comment]
IP 10.228.18.49 (guifi) 192.168.1.2 (local)
User/password: guifibages/el de sempre

Esta dins una maquina virtual gestionada amb proxmox. S'hi pot accedir
utilitzant la IP 192.168.1.3 des de l'escriptori remot a
lluismillet.guifibages.net.

El virtual està connectat al router de Fibracat que té IP 213.148.199.20 i
on es redirigeixen els ports quan es necessari, si necessites user i pass
te'ls envio per privat.
El dia 22 abr. 2016 12:56 a. m., "Ignacio Torres Masdeu" <
notifications@github.com> va escriure:
